name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: "http://0.0.0.0:8000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r bookstore/requirements.txt
          pip install pytest pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/bookstore" >> $GITHUB_ENV

      - name: Start Uvicorn Server
        run: |
          source venv/bin/activate
          uvicorn bookstore.main:app --host 0.0.0.0 --port 8000 --reload &
        env:
          PYTHONUNBUFFERED: 1

      - name: Wait for API to be Ready
        run: sleep 5

      - name: Run Unit Tests with Coverage
        run: |
          source venv/bin/activate
          pytest --cov=bookstore --cov-report=html bookstore/tests/

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Stop Uvicorn Server
        run: |
          pkill -f "uvicorn"
